spring.application.name=event-ingestion-service
server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/sportsbetting}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sportsbetting}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:sportsbetting}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:19092}

management.tracing.sampling.probability=1.0
management.endpoints.web.exposure.include=health,info,metrics,prometheus
spring.kafka.template.observation-enabled=true
spring.kafka.listener.observation-enabled=true

app.kafka.schema-validation.enabled=${APP_KAFKA_SCHEMA_VALIDATION_ENABLED:false}
